language: node_js

node_js:
  - 8.9.1

install:
  - brew install ccache
  - brew install libpng
#  - export PATH="/usr/local/opt/ccache/libexec:$PATH"

script:
  - npm run build

before_install:
  #- yarn global add cross-env@5.0.5 webpack

notifications:
  email:
    on_failure: change

# after_success: 'npm run coveralls'

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/Library/Caches/Homebrew

os: osx