language: node_js

node_js:
  - 8

script:
  - npm run build:dll
  - npm run build

before_install:
  - brew install libpng
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email:
    on_failure: change

# after_success: 'npm run coveralls'

cache:
  yarn: true
  directories:
    - node_modules
os: osx