language: node_js

node_js:
  - 8

script:
  - yarn add -D cross-env
  - npm run build:dll
  - npm run build

before_install:
  - brew install libpng

notifications:
  email:
    on_failure: change

# after_success: 'npm run coveralls'

cache:
  yarn: true
  directories:
    - node_modules
os: osx